name = "AlgebraicEpiMech"
uuid = "a6e39d6b-8b2d-49f3-aca0-f4154643f040"
version = "0.1.0"
authors = ["Samuel Brand <usi1@cdc.gov>"]

[workspace]
projects = ["test"]

[deps]
AlgebraicPetri = "4f99eebe-17bf-4e98-b6a1-2c4f205a959b"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
AlgebraicPetri = "0.10.0"
Catlab = "0.17.2"
DocStringExtensions = "0.9.3"
julia = "1.11, 1.12, 1.13"
