using ConfigurableEpi, Test

include("aqua.jl")
include("test_param_spec.jl")
include("test_ekp_parameter_distributions.jl")
include("test_seasonality.jl")
include("test_ascertainment.jl")
include("test_day_of_week.jl")
include("test_ascertainment_trend.jl")
include("test_state_layout.jl")
include("test_latent_dynamics.jl")
include("test_measurement_model.jl")
include("test_observation_logpdf.jl")
include("test_core_dynamics.jl")
include("test_full_dynamics.jl")
include("test_pf_builders.jl")
include("test_hyperparam_learning.jl")
include("test_arrival_process.jl")
include("test_redistribute_jumps.jl")
include("test_backtest.jl")
include("test_augmented_enkf.jl")
include("test_build_inference.jl")
include("test_data_linkage.jl")
include("test_closure_boxing.jl")
include("test_dual_numbers.jl")
